"""
Loads the official AASIST-L architecture and pretrained checkpoint, and
runs inference to produce a synthetic-speech probability.

Checkpoint provenance (do not change without re-verifying against the
source):
    - Source: https://github.com/clovaai/aasist (official, NAVER Corp)
    - File:   models/weights/AASIST-L.pth (copied verbatim into
              models/deepfake/weights/AASIST-L.pth in this repo)
    - License: MIT (see weights/AASIST_LICENSE)
    - Trained on: ASVspoof 2019 Logical Access (LA) -- synthetic/converted
      speech generated by ~19 TTS/VC systems, English, studio-quality
      source audio. It was NOT trained on real phone-call audio or on
      modern voice-cloning tools (e.g. ElevenLabs-style cloning).
    - Reported performance (from the official model card / benchmark,
      not measured by us): EER 0.99% on ASVspoof2019 LA (in-domain),
      but 13.15% on ASVspoof2021 LA and 15.96% on ASVspoof2021 DF
      (out-of-domain / unseen attacks) -- meaningfully worse than the
      in-domain number. Treat the in-domain figure as a ceiling, not an
      expectation for this project's real-world audio.
    - Input: raw waveform, float32, 16kHz, fixed length 64600 samples
      (see features.py). Model has its own learned SincNet-style front
      end -- no external LFCC/spectrogram extraction is required.
    - Output: 2 logits (index 0 = spoof, index 1 = bonafide). The official
      eval code uses the raw bonafide logit as a threshold-based score for
      EER computation -- it is NOT a calibrated probability. We apply a
      softmax to get a probability-shaped number, which is more useful for
      a 0.0-1.0 API, but this is a modeling choice on our part, not a
      property the checkpoint was designed to have. It should not be
      read as "X% confident" until we calibrate it on our own held-out
      real/synthetic test data.
"""
from __future__ import annotations

import os

import numpy as np

_WEIGHTS_PATH = os.path.join(os.path.dirname(__file__), "weights", "AASIST-L.pth")

# Exact copy of config/AASIST-L.conf's "model_config" block from the
# official repo -- do not change without re-checking that file, since these
# values must match the shapes baked into the checkpoint.
_AASIST_L_CONFIG = {
    "architecture": "AASIST",
    "nb_samp": 64600,
    "first_conv": 128,
    "filts": [70, [1, 32], [32, 32], [32, 24], [24, 24]],
    "gat_dims": [24, 32],
    "pool_ratios": [0.4, 0.5, 0.7, 0.5],
    "temperatures": [2.0, 2.0, 100.0, 100.0],
}


class ModelUnavailableError(RuntimeError):
    """Raised when torch/the checkpoint can't be loaded."""


class AASISTAdapter:
    """
    Thin wrapper around the vendored AASIST architecture. Loads the model
    once (in __init__) and reuses it for every prediction call, so we don't
    pay model-load cost per audio window.
    """

    def __init__(self, weights_path: str = _WEIGHTS_PATH, device: str = "cpu"):
        try:
            import torch
        except ImportError as exc:
            raise ModelUnavailableError(
                "PyTorch is required to run the AASIST-L model. "
                "Install it with: pip install torch --index-url "
                "https://download.pytorch.org/whl/cpu"
            ) from exc

        from ._aasist_arch import Model as _AASISTModel

        if not os.path.exists(weights_path):
            raise ModelUnavailableError(
                f"checkpoint not found at {weights_path}. This project "
                "does not fabricate a working model when the real "
                "checkpoint is missing -- restore weights/AASIST-L.pth "
                "from https://github.com/clovaai/aasist before running."
            )

        self._torch = torch
        self.device = torch.device(device)
        self.model = _AASISTModel(_AASIST_L_CONFIG)
        state_dict = torch.load(weights_path, map_location=self.device)
        self.model.load_state_dict(state_dict)
        self.model.to(self.device)
        self.model.eval()

    def predict(self, waveform: np.ndarray) -> float:
        """
        waveform: float32 numpy array, shape (64600,), already padded by
        features.pad_to_fixed_length.

        Returns synthetic_probability in [0.0, 1.0]: softmax probability
        mass on the "spoof" logit (index 0).
        """
        torch = self._torch
        with torch.no_grad():
            x = torch.from_numpy(waveform).float().unsqueeze(0).to(self.device)
            _, logits = self.model(x)  # (1, 2): [spoof_logit, bonafide_logit]
            probs = torch.softmax(logits, dim=1)
            synthetic_probability = float(probs[0, 0].item())
        return synthetic_probability
